/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GuiEditor.java
 *
 * Created on Dec 14, 2010, 7:51:51 PM
 */

package jellyfish.base.gui;

import java.io.File;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.JFrame;
import jellyfish.base.JellyfishBase;
import jellyfish.common.CaseInsensitiveStringComparator;

/**
 *
 * @author Xevia
 */
public class GuiEditor extends javax.swing.JFrame {

	private SemNetEditorFrame semNetEditorFrame;
	private JellyfishBase jellyfishBase;
	private Map<String,ClauseEditorFrame> clauseEditorFrames;

    /** Creates new form GuiEditor */
    public GuiEditor( File semNetFile ) throws Exception {
		semNetEditorFrame = new SemNetEditorFrame( this, semNetFile );
		jellyfishBase = semNetEditorFrame.getJellyfishBase();
		clauseEditorFrames = new TreeMap<String, ClauseEditorFrame>(new CaseInsensitiveStringComparator());
		for (String language:jellyfishBase.getLanguages()) {
			clauseEditorFrames.put( language, new ClauseEditorFrame( this, jellyfishBase, language ) );
		}

		initComponents();

		tabbedPane.add( "Semantic Net", semNetEditorFrame );
		for (String language:jellyfishBase.getLanguages()) {
			System.out.println( "Adding Language Tab: "+language );
			tabbedPane.add( language, clauseEditorFrames.get( language ) );
		}

		this.setExtendedState( JFrame.MAXIMIZED_BOTH );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        getContentPane().add(tabbedPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
				try {
					File semNetFile = new File( "semnet.xml" );
					GuiEditor editor = new GuiEditor( semNetFile );
					editor.setVisible( true );
				} catch ( Exception ex ) {
					ex.printStackTrace( System.out );
				}
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables

}
