/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConnectorsPanel.java
 *
 * Created on Nov 9, 2010, 11:51:04 PM
 */

package jellyfish.editor;

import java.awt.Component;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.persistence.EntityManager;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JFrame;
import javax.swing.JList;
import jellyfish.common.persistence.PersistenceUtil;
import jellyfish.editor.controller.ConnectorController;
import jellyfish.editor.controller.PersistenceContext;
import jellyfish.editor.controller.RelationshipController;
import jellyfish.editor.model.Connector;

/**
 *
 * @author Xevia
 */
public class ConnectorsPanel extends javax.swing.JPanel {

    private JFrame frame;
    private ConnectorController controller;

    /** Creates new form ConnectorsPanel */
    public ConnectorsPanel(JFrame frame, ConnectorController controller) {
        this.frame = frame;
        this.controller = controller;
        initComponents();
    }

    public ConnectorController getController() {
        return controller;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        txtSubject = new javax.swing.JLabel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        txtPredicate = new javax.swing.JLabel();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        txtObject = new javax.swing.JLabel();
        jellyfish.editor.HorizontalLine horizontalLine3 = new jellyfish.editor.HorizontalLine();
        jPanel4 = new javax.swing.JPanel();
        btnDelConnectors = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(2000, 25));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 25));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 12));
        jLabel1.setText("Subject:");
        jLabel1.setMaximumSize(new java.awt.Dimension(80, 25));
        jLabel1.setMinimumSize(new java.awt.Dimension(80, 25));
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 25));
        jPanel1.add(jLabel1, java.awt.BorderLayout.WEST);

        txtSubject.setFont(new java.awt.Font("Lucida Sans", 0, 12));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${controller.selectedConnector.triple.subject.name}"), txtSubject, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(txtSubject, java.awt.BorderLayout.CENTER);

        add(jPanel1);

        jPanel2.setMaximumSize(new java.awt.Dimension(2000, 25));
        jPanel2.setMinimumSize(new java.awt.Dimension(200, 25));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 12));
        jLabel2.setText("Predicate:");
        jLabel2.setMaximumSize(new java.awt.Dimension(80, 25));
        jLabel2.setMinimumSize(new java.awt.Dimension(80, 25));
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 25));
        jPanel2.add(jLabel2, java.awt.BorderLayout.WEST);

        txtPredicate.setFont(new java.awt.Font("Lucida Sans", 0, 12));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${controller.selectedConnector.triple.predicate.name}"), txtPredicate, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel2.add(txtPredicate, java.awt.BorderLayout.CENTER);

        add(jPanel2);

        jPanel3.setMaximumSize(new java.awt.Dimension(2000, 25));
        jPanel3.setMinimumSize(new java.awt.Dimension(200, 25));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 12));
        jLabel3.setText("Object:");
        jLabel3.setMaximumSize(new java.awt.Dimension(80, 25));
        jLabel3.setMinimumSize(new java.awt.Dimension(80, 25));
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 25));
        jPanel3.add(jLabel3, java.awt.BorderLayout.WEST);

        txtObject.setFont(new java.awt.Font("Lucida Sans", 0, 12));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${controller.selectedConnector.triple.object.name}"), txtObject, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel3.add(txtObject, java.awt.BorderLayout.CENTER);

        add(jPanel3);

        horizontalLine3.setForeground(new java.awt.Color(153, 153, 153));
        horizontalLine3.setPreferredSize(new java.awt.Dimension(10, 1));

        javax.swing.GroupLayout horizontalLine3Layout = new javax.swing.GroupLayout(horizontalLine3);
        horizontalLine3.setLayout(horizontalLine3Layout);
        horizontalLine3Layout.setHorizontalGroup(
            horizontalLine3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        horizontalLine3Layout.setVerticalGroup(
            horizontalLine3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        add(horizontalLine3);

        jPanel4.setMaximumSize(new java.awt.Dimension(2000, 35));
        jPanel4.setPreferredSize(new java.awt.Dimension(110, 35));

        btnDelConnectors.setText("Delete");
        btnDelConnectors.setMaximumSize(new java.awt.Dimension(100, 25));
        btnDelConnectors.setMinimumSize(new java.awt.Dimension(100, 25));
        btnDelConnectors.setPreferredSize(new java.awt.Dimension(100, 25));
        btnDelConnectors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelConnectorsActionPerformed(evt);
            }
        });
        jPanel4.add(btnDelConnectors);

        add(jPanel4);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDelConnectorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelConnectorsActionPerformed

        synchronized (controller.getItemList()) {
            if (controller.getSelectedConnector()!=null) {
                controller.getItemList().remove(controller.getSelectedConnector());
            }
        }


    }//GEN-LAST:event_btnDelConnectorsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelConnectors;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel txtObject;
    private javax.swing.JLabel txtPredicate;
    private javax.swing.JLabel txtSubject;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables


    public static void main(String[] args) {
        try {
//            final EntityManager em = PersistenceUtil.getEntityManager(true, true);
            final EntityManager em = PersistenceUtil.getEntityManager(false, false);

            final PersistenceContext context = new PersistenceContext(em);
            final ConnectorController controller = new ConnectorController(context);

            if (em==null) {
                System.out.println("ERROR: Unintialized EntityManager");
                return;
            }

            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    JFrame mainFrame = new JFrame();
                    ConnectorsPanel panel = new ConnectorsPanel(mainFrame, controller);
                    mainFrame.setContentPane(panel);
                    mainFrame.pack();
                    mainFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    mainFrame.addWindowListener(new WindowAdapter() {
                        @Override
                        public void windowClosing(WindowEvent e) {
                            context.save();
                        }
                    });
                    mainFrame.setVisible(true);
                }
            });

        } catch (Exception e) {
            e.printStackTrace( System.out );
        }
    }
    
}
