/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame2.java
 *
 * Created on Nov 4, 2010, 9:45:05 PM
 */

package jellyfish.editor;

import com.sun.java.swing.plaf.windows.WindowsDesktopManager;
import java.awt.Color;
import java.awt.Point;
import javax.persistence.EntityManager;
import javax.swing.JDialog;
import javax.swing.JInternalFrame;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import jellyfish.common.persistence.PersistenceUtil;
import jellyfish.editor.controller.ConnectorController;
import jellyfish.editor.controller.EntityBoxController;
import jellyfish.editor.controller.PersistenceContext;
import jellyfish.editor.controller.RelationshipController;

/**
 *
 * @author Xevia
 */
class MainFrame extends javax.swing.JFrame {

    private PersistenceContext context;
    private RelationshipController relationshipsController;
    private EntityBoxController entityBoxController;
    private ConnectorController connectorController;

//    private PanelDiagram panelDiagram;
    private RelationshipsPanel relationshipsPanel;
    private EntityBoxPanel2 entityBoxPanel;
    private ConnectorsPanel connectorsPanel;

    private JInternalFrame connectorsFrame;
    private JDialog relationshipsDlg;
    private JDialog entityBoxDlg;

    /** Creates new form MainFrame2 */
    public MainFrame(PersistenceContext context) {

        this.context = context;
        this.relationshipsController = new RelationshipController(context);
        this.entityBoxController = new EntityBoxController(context);
        this.connectorController = new ConnectorController(context);

        initComponents();
        init();
    }
    
    private void init() {

        semNetDesktop.setDesktopManager(new WindowsDesktopManager() {

            @Override
            public void iconifyFrame(JInternalFrame f) {
                super.iconifyFrame(f);
                Point pt = f.getLocation();
                if (!f.isMaximum()) {
                    f.getDesktopIcon().setLocation(pt);
                }
            }

            @Override
            public void deiconifyFrame(JInternalFrame f) {
                super.deiconifyFrame(f);
                Point pt = f.getDesktopIcon().getLocation();
                f.setLocation(pt);
            }

            
            
        });

        relationshipsPanel = new RelationshipsPanel(this, relationshipsController);
        entityBoxPanel = new EntityBoxPanel2(this, entityBoxController, connectorController);
        connectorsPanel = new ConnectorsPanel(this, connectorController);

        connectorsFrame = putIntoPaletteFrame("Triples", connectorsPanel);
        connectorsFrame.setLocation(10, 10);
        connectorsFrame.setVisible(true);

        relationshipsDlg = putIntoDialogFrame("Predicates", relationshipsPanel);
        entityBoxDlg = putIntoDialogFrame("Entities", entityBoxPanel);
        
        semNetDesktop.validate();
        semNetDesktop.repaint();
    }

    private JInternalFrame putIntoPaletteFrame(String title, JPanel panel)
    {
        JInternalFrame frame = new JInternalFrame(title, false, false, false, true);
        frame.setContentPane(panel);
        frame.setBackground(new Color(204, 204, 255));
        frame.setLayer(JLayeredPane.PALETTE_LAYER);
        frame.pack();
        semNetDesktop.add(frame, JLayeredPane.PALETTE_LAYER);
        return frame;
    }
    
    private JDialog putIntoDialogFrame(String title, JPanel panel)
    {
        JDialog frame = new JDialog();
        frame.setTitle(title);
        frame.setContentPane(panel);
        frame.setBackground(new Color(204, 204, 255));
        frame.pack();
        frame.setLocationRelativeTo(this);
        return frame;
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        semNetEditorPane = new javax.swing.JPanel();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        btnEditRelationships = new javax.swing.JButton();
        btnEditEntities = new javax.swing.JButton();
        jPanel2 = new NewEntityDragPanel(this);
        semNetDesktop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        semNetEditorPane.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        btnEditRelationships.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnEditRelationships.setText("Edit Relationships");
        btnEditRelationships.setMaximumSize(new java.awt.Dimension(150, 25));
        btnEditRelationships.setMinimumSize(new java.awt.Dimension(150, 25));
        btnEditRelationships.setPreferredSize(new java.awt.Dimension(150, 25));
        btnEditRelationships.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditRelationshipsActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditRelationships);

        btnEditEntities.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnEditEntities.setText("Edit Entities");
        btnEditEntities.setMaximumSize(new java.awt.Dimension(150, 25));
        btnEditEntities.setMinimumSize(new java.awt.Dimension(150, 25));
        btnEditEntities.setPreferredSize(new java.awt.Dimension(150, 25));
        btnEditEntities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditEntitiesActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditEntities);

        jPanel2.setMaximumSize(new java.awt.Dimension(150, 25));
        jPanel2.setMinimumSize(new java.awt.Dimension(150, 25));
        jPanel2.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel1.add(jPanel2);

        semNetEditorPane.add(jPanel1, java.awt.BorderLayout.NORTH);
        semNetEditorPane.add(semNetDesktop, java.awt.BorderLayout.CENTER);

        tabbedPane.addTab("Semantic Network", semNetEditorPane);

        getContentPane().add(tabbedPane, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-616)/2, (screenSize.height-701)/2, 616, 701);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

//        persitenceContext.save();

    }//GEN-LAST:event_formWindowClosing

    private void btnEditRelationshipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditRelationshipsActionPerformed

        relationshipsDlg.setVisible(true);

    }//GEN-LAST:event_btnEditRelationshipsActionPerformed

    private void btnEditEntitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditEntitiesActionPerformed

        entityBoxDlg.setVisible(true);

    }//GEN-LAST:event_btnEditEntitiesActionPerformed

//    /**
//    * @param args the command line arguments
//    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditEntities;
    private javax.swing.JButton btnEditRelationships;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JDesktopPane semNetDesktop;
    private javax.swing.JPanel semNetEditorPane;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables


    public static void main(String[] args) {
        try {
//            final EntityManager em = PersistenceUtil.getEntityManager(true, true);
            final EntityManager em = PersistenceUtil.getEntityManager(false, false);
            
            if (em==null) {
                System.out.println("ERROR: Unintialized EntityManager");
                return;
            }

            final PersistenceContext context = new PersistenceContext(em);

            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    MainFrame mainFrame = new MainFrame(context);
                    mainFrame.setVisible(true);
                }
            });

        } catch (Exception e) {
            e.printStackTrace( System.out );
        }
    }
    
}
