/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelEntityBox.java
 *
 * Created on Oct 31, 2010, 3:50:55 AM
 */

package jellyfish.editor;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;
import jellyfish.editor.model.EntityBox;

/**
 *
 * @author Xevia
 */
public class PanelEntityBox extends javax.swing.JPanel {

    private JFrame frame;
    private EntityBox entityBox;

    /** Creates new form PanelEntityBox */
    public PanelEntityBox(JFrame frame, EntityBox entityBox) {
        this.frame = frame;
        this.entityBox = entityBox;
        initComponents();
        this.setSize(this.getPreferredSize());
    }

    public EntityBox getEntityBox() {
        return entityBox;
    }

    public JPanel getDragPanel() {
        return dragPanel;
    }

    public JPanel getLinkPanel() {
        return linkPanel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        lblEntityName = new javax.swing.JLabel();
        jellyfish.editor.HorizontalLine horizontalLine1 = new jellyfish.editor.HorizontalLine();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        dragPanel = new DragPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        linkPanel = new DragPanel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                formComponentMoved(evt);
            }
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(200, 25));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.setLayout(new java.awt.BorderLayout());

        lblEntityName.setFont(new java.awt.Font("Lucida Sans", 1, 12));
        lblEntityName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEntityName.setName("lblEntityName"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, this, org.jdesktop.beansbinding.ELProperty.create("${entityBox.entity.name}"), lblEntityName, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(lblEntityName, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jPanel1, gridBagConstraints);

        horizontalLine1.setName("horizontalLine1"); // NOI18N
        horizontalLine1.setPreferredSize(new java.awt.Dimension(100, 1));

        javax.swing.GroupLayout horizontalLine1Layout = new javax.swing.GroupLayout(horizontalLine1);
        horizontalLine1.setLayout(horizontalLine1Layout);
        horizontalLine1Layout.setHorizontalGroup(
            horizontalLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        horizontalLine1Layout.setVerticalGroup(
            horizontalLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(horizontalLine1, gridBagConstraints);

        jPanel3.setMinimumSize(new java.awt.Dimension(80, 35));
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(80, 35));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnEdit.setFont(new java.awt.Font("Lucida Sans", 0, 10));
        btnEdit.setText("Edit");
        btnEdit.setMaximumSize(new java.awt.Dimension(55, 25));
        btnEdit.setMinimumSize(new java.awt.Dimension(55, 25));
        btnEdit.setName("btnEdit"); // NOI18N
        btnEdit.setPreferredSize(new java.awt.Dimension(55, 25));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel3.add(btnEdit);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jPanel3, gridBagConstraints);

        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 35));
        jPanel2.setMinimumSize(new java.awt.Dimension(10, 35));
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(10, 35));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        dragPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dragPanel.setMaximumSize(new java.awt.Dimension(90, 25));
        dragPanel.setMinimumSize(new java.awt.Dimension(90, 25));
        dragPanel.setName("dragPanel"); // NOI18N
        dragPanel.setPreferredSize(new java.awt.Dimension(40, 25));
        dragPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 10));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Move");
        jLabel1.setName("jLabel1"); // NOI18N
        dragPanel.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel2.add(dragPanel);

        linkPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        linkPanel.setMaximumSize(new java.awt.Dimension(90, 25));
        linkPanel.setMinimumSize(new java.awt.Dimension(90, 25));
        linkPanel.setName("linkPanel"); // NOI18N
        linkPanel.setPreferredSize(new java.awt.Dimension(40, 25));
        linkPanel.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 10));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Link");
        jLabel2.setName("jLabel2"); // NOI18N
        linkPanel.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel2.add(linkPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(jPanel2, gridBagConstraints);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

        
        final JDialog dialog = new JDialog(frame);

        EntityEditor editor = new EntityEditor(null, entityBox.getEntity()) {
            @Override
            protected void closeDialog() {
                dialog.setVisible(false);
            }
        };
        dialog.setContentPane(editor);
        dialog.pack();
        
        dialog.setLocationRelativeTo(frame);
        dialog.setModal(true);
        dialog.setVisible(true);

    }//GEN-LAST:event_btnEditActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized

        entityBox.setWidth(this.getWidth());
        entityBox.setHeight(this.getHeight());

    }//GEN-LAST:event_formComponentResized

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved

        entityBox.setX(this.getX());
        entityBox.setY(this.getY());

    }//GEN-LAST:event_formComponentMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JPanel dragPanel;
    private javax.swing.JLabel lblEntityName;
    private javax.swing.JPanel linkPanel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    @Override
    public String toString() {
        return entityBox.toString();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final PanelEntityBox other = (PanelEntityBox) obj;
        if (this.entityBox != other.entityBox && (this.entityBox == null || !this.entityBox.equals(other.entityBox))) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        return this.entityBox.hashCode();
    }



}
