/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RelationshipsPanel.java
 *
 * Created on Nov 9, 2010, 10:59:33 PM
 */

package jellyfish.editor;

import java.awt.Component;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.persistence.EntityManager;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import jellyfish.common.persistence.PersistenceUtil;
import jellyfish.editor.controller.PersistenceContext;
import jellyfish.editor.controller.RelationshipController;
import jellyfish.triplestore.model.Relationship;

/**
 *
 * @author Xevia
 */
public class RelationshipsPanel extends javax.swing.JPanel {

    private JFrame frame;
    private RelationshipController controller;

    /** Creates new form RelationshipsPanel */
    public RelationshipsPanel(JFrame frame, RelationshipController controller) {
        this.frame = frame;
        this.controller =  controller;
        initComponents();
        
        bindingGroup.addBindingListener(new BindingFailureListener(txtErrorMsg));

    }

    public RelationshipController getController() {
        return controller;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        javax.swing.JPanel jPanel6 = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        listRelationships = new javax.swing.JList();
        jellyfish.editor.HorizontalLine horizontalLine1 = new jellyfish.editor.HorizontalLine();
        javax.swing.JPanel jPanel5 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        txtSelectedRelName = new javax.swing.JTextField();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        chkSymmetric = new javax.swing.JCheckBox();
        chkTransitive = new javax.swing.JCheckBox();
        jellyfish.editor.HorizontalLine horizontalLine2 = new jellyfish.editor.HorizontalLine();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        btnRelAdd = new javax.swing.JButton();
        btnRelDel = new javax.swing.JButton();
        jellyfish.editor.HorizontalLine horizontalLine3 = new jellyfish.editor.HorizontalLine();
        javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
        chkHighlightRelationship = new javax.swing.JToggleButton();
        jellyfish.editor.HorizontalLine horizontalLine4 = new jellyfish.editor.HorizontalLine();
        javax.swing.JPanel jPanel7 = new javax.swing.JPanel();
        txtErrorMsg = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 5, 1));
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setMaximumSize(new java.awt.Dimension(32767, 100));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(100, 100));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(100, 100));

        listRelationships.setFont(new java.awt.Font("Lucida Sans", 0, 12));
        listRelationships.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listRelationships.setCellRenderer(new ListRelationshipRenderer());

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${controller.itemList}");
        org.jdesktop.swingbinding.JListBinding jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, this, eLProperty, listRelationships);
        jListBinding.setSourceNullValue(null);
        jListBinding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(jListBinding);
        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${controller.selectedItemIndex}"), listRelationships, org.jdesktop.beansbinding.BeanProperty.create("selectedIndex"));
        binding.setSourceNullValue(null);
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);

        listRelationships.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listRelationshipsValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listRelationships);

        jPanel6.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(jPanel6);

        horizontalLine1.setForeground(new java.awt.Color(153, 153, 153));
        horizontalLine1.setPreferredSize(new java.awt.Dimension(10, 1));

        javax.swing.GroupLayout horizontalLine1Layout = new javax.swing.GroupLayout(horizontalLine1);
        horizontalLine1.setLayout(horizontalLine1Layout);
        horizontalLine1Layout.setHorizontalGroup(
            horizontalLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        horizontalLine1Layout.setVerticalGroup(
            horizontalLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        add(horizontalLine1);

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 5, 1));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setMaximumSize(new java.awt.Dimension(2000, 25));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 12));
        jLabel2.setText("Name:");
        jLabel2.setMinimumSize(new java.awt.Dimension(50, 16));
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel2.add(jLabel2, java.awt.BorderLayout.WEST);

        txtSelectedRelName.setFont(new java.awt.Font("Lucida Sans", 0, 12));
        txtSelectedRelName.setMinimumSize(new java.awt.Dimension(69, 25));
        txtSelectedRelName.setPreferredSize(new java.awt.Dimension(69, 25));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${controller.selectedRelationship.name}"), txtSelectedRelName, org.jdesktop.beansbinding.BeanProperty.create("text_ON_ACTION_OR_FOCUS_LOST"));
        binding.setSourceNullValue("");
        binding.setSourceUnreadableValue("");
        binding.setValidator(controller.getContext().new BaseEntityNameValidator());
        bindingGroup.addBinding(binding);

        jPanel2.add(txtSelectedRelName, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel2);

        jPanel3.setMaximumSize(new java.awt.Dimension(2000, 25));
        jPanel3.setMinimumSize(new java.awt.Dimension(210, 25));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(210, 25));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        chkSymmetric.setFont(new java.awt.Font("Lucida Sans", 0, 12));
        chkSymmetric.setText("Symmetric");
        chkSymmetric.setMaximumSize(new java.awt.Dimension(100, 25));
        chkSymmetric.setMinimumSize(new java.awt.Dimension(100, 25));
        chkSymmetric.setOpaque(false);
        chkSymmetric.setPreferredSize(new java.awt.Dimension(100, 25));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${controller.selectedRelationship.symmetric}"), chkSymmetric, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        jPanel3.add(chkSymmetric);

        chkTransitive.setFont(new java.awt.Font("Lucida Sans", 0, 12));
        chkTransitive.setText("Transitive");
        chkTransitive.setMaximumSize(new java.awt.Dimension(100, 25));
        chkTransitive.setMinimumSize(new java.awt.Dimension(100, 25));
        chkTransitive.setOpaque(false);
        chkTransitive.setPreferredSize(new java.awt.Dimension(100, 25));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${controller.selectedRelationship.transitive}"), chkTransitive, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        jPanel3.add(chkTransitive);

        jPanel5.add(jPanel3);

        add(jPanel5);

        horizontalLine2.setForeground(new java.awt.Color(153, 153, 153));
        horizontalLine2.setPreferredSize(new java.awt.Dimension(10, 1));

        javax.swing.GroupLayout horizontalLine2Layout = new javax.swing.GroupLayout(horizontalLine2);
        horizontalLine2.setLayout(horizontalLine2Layout);
        horizontalLine2Layout.setHorizontalGroup(
            horizontalLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        horizontalLine2Layout.setVerticalGroup(
            horizontalLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        add(horizontalLine2);

        jPanel1.setMaximumSize(new java.awt.Dimension(2000, 25));
        jPanel1.setOpaque(false);

        btnRelAdd.setFont(new java.awt.Font("Lucida Sans", 0, 10));
        btnRelAdd.setText("Add");
        btnRelAdd.setMaximumSize(new java.awt.Dimension(60, 25));
        btnRelAdd.setMinimumSize(new java.awt.Dimension(60, 25));
        btnRelAdd.setOpaque(false);
        btnRelAdd.setPreferredSize(new java.awt.Dimension(60, 25));
        btnRelAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnRelAdd);

        btnRelDel.setFont(new java.awt.Font("Lucida Sans", 0, 10));
        btnRelDel.setText("Del");
        btnRelDel.setMaximumSize(new java.awt.Dimension(60, 25));
        btnRelDel.setMinimumSize(new java.awt.Dimension(60, 25));
        btnRelDel.setOpaque(false);
        btnRelDel.setPreferredSize(new java.awt.Dimension(60, 25));
        btnRelDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelDelActionPerformed(evt);
            }
        });
        jPanel1.add(btnRelDel);

        add(jPanel1);

        horizontalLine3.setForeground(new java.awt.Color(153, 153, 153));
        horizontalLine3.setPreferredSize(new java.awt.Dimension(10, 1));

        javax.swing.GroupLayout horizontalLine3Layout = new javax.swing.GroupLayout(horizontalLine3);
        horizontalLine3.setLayout(horizontalLine3Layout);
        horizontalLine3Layout.setHorizontalGroup(
            horizontalLine3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        horizontalLine3Layout.setVerticalGroup(
            horizontalLine3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        add(horizontalLine3);

        jPanel4.setMaximumSize(new java.awt.Dimension(2000, 35));
        jPanel4.setOpaque(false);

        chkHighlightRelationship.setFont(new java.awt.Font("Lucida Sans", 0, 12));
        chkHighlightRelationship.setText("Highlight");
        chkHighlightRelationship.setPreferredSize(new java.awt.Dimension(150, 25));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${controller.highlightRelationship}"), chkHighlightRelationship, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        jPanel4.add(chkHighlightRelationship);

        add(jPanel4);

        horizontalLine4.setForeground(new java.awt.Color(153, 153, 153));
        horizontalLine4.setPreferredSize(new java.awt.Dimension(10, 1));

        javax.swing.GroupLayout horizontalLine4Layout = new javax.swing.GroupLayout(horizontalLine4);
        horizontalLine4.setLayout(horizontalLine4Layout);
        horizontalLine4Layout.setHorizontalGroup(
            horizontalLine4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        horizontalLine4Layout.setVerticalGroup(
            horizontalLine4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        add(horizontalLine4);

        jPanel7.setMaximumSize(new java.awt.Dimension(2000, 30));
        jPanel7.setMinimumSize(new java.awt.Dimension(100, 30));
        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel7.setLayout(new java.awt.BorderLayout());

        txtErrorMsg.setFont(new java.awt.Font("Lucida Sans", 1, 10));
        txtErrorMsg.setForeground(new java.awt.Color(153, 0, 0));
        txtErrorMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel7.add(txtErrorMsg, java.awt.BorderLayout.CENTER);

        add(jPanel7);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRelAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelAddActionPerformed

        String name = JOptionPane.showInputDialog(this, "Please enter predicate name");
        if (name == null || name.isEmpty()) {
            return;
        }

        if (controller.getContext().nameExists(name)) {
            JOptionPane.showMessageDialog(this, "Name '" + name + "' is already in use.");
            return;
        }

        Relationship relationship = new Relationship(name, false, false);

        controller.getItemList().add(relationship);

    }//GEN-LAST:event_btnRelAddActionPerformed

    private void btnRelDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelDelActionPerformed

        Relationship relationship = (Relationship) listRelationships.getSelectedValue();
        if (relationship == null) {
            JOptionPane.showMessageDialog(this, "Please select a predicate first");
            return;
        }

        controller.getItemList().remove(relationship);

    }//GEN-LAST:event_btnRelDelActionPerformed

    private void listRelationshipsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listRelationshipsValueChanged

        if (!evt.getValueIsAdjusting())
            controller.setSelectedRelationship((Relationship)listRelationships.getSelectedValue());

    }//GEN-LAST:event_listRelationshipsValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRelAdd;
    private javax.swing.JButton btnRelDel;
    private javax.swing.JToggleButton chkHighlightRelationship;
    private javax.swing.JCheckBox chkSymmetric;
    private javax.swing.JCheckBox chkTransitive;
    private javax.swing.JList listRelationships;
    private javax.swing.JLabel txtErrorMsg;
    private javax.swing.JTextField txtSelectedRelName;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private class ListRelationshipRenderer extends DefaultListCellRenderer {
        
        @Override
        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            Relationship r = (Relationship)value;
            return super.getListCellRendererComponent(list, r.getName(), index, isSelected, cellHasFocus);
        }

    }

    public static void main(String[] args) {
        try {
//            final EntityManager em = PersistenceUtil.getEntityManager(true, true);
            final EntityManager em = PersistenceUtil.getEntityManager(false, false);
            
            final PersistenceContext context = new PersistenceContext(em);
            final RelationshipController controller = new RelationshipController(context);
            
            if (em==null) {
                System.out.println("ERROR: Unintialized EntityManager");
                return;
            }

            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    JFrame mainFrame = new JFrame();
                    RelationshipsPanel panel = new RelationshipsPanel(mainFrame, controller);
                    mainFrame.setContentPane(panel);
                    mainFrame.pack();
                    mainFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    
                    mainFrame.addWindowListener(new WindowAdapter() {
                        @Override
                        public void windowClosing(WindowEvent e) {
                            context.save();
                        }
                    });

                    mainFrame.setVisible(true);
                }
            });

        } catch (Exception e) {
            e.printStackTrace( System.out );
        }
    }

    
}
