/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * XmlEditor.java
 *
 * Created on Nov 7, 2010, 9:06:44 PM
 */

package jellyfish.editor;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import jellyfish.common.Common;

/**
 *
 * @author Xevia
 */
public class XmlEditor extends javax.swing.JPanel {

    private static final String XML_FILE_NAME = "parser.xml";

    /** Creates new form XmlEditor */
    public XmlEditor() {
        initComponents();
        reloadXml();
    }

    private void reloadXml()
    {
        FileInputStream fileInputStream = null;
        
        try {
            fileInputStream = new FileInputStream(XML_FILE_NAME);
            String contents = Common.streamToString(fileInputStream);
            txtXml.setText(contents);
            txtXml.setEditable(true);
        } catch (Exception ex) {
            ex.printStackTrace(System.out);
            txtXml.setEditable(false);
        } finally {
            if (fileInputStream!=null) {
                try {
                    fileInputStream.close();
                } catch (Exception ex) {
                }
            }
        }
    }

    private void saveXml()
    {
        FileWriter fileWriter = null;

        try {
            fileWriter = new FileWriter(XML_FILE_NAME);
            fileWriter.append(txtXml.getText());
        } catch (Exception ex) {
            ex.printStackTrace(System.out);
        } finally {
            if (fileWriter!=null) {
                try {
                    fileWriter.close();
                } catch (Exception ex) {
                }
            }
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnReloadXml = new javax.swing.JButton();
        btnSaveXml = new javax.swing.JButton();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        txtXml = new org.fife.ui.rsyntaxtextarea.RSyntaxTextArea();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnReloadXml.setFont(new java.awt.Font("Lucida Sans", 0, 10)); // NOI18N
        btnReloadXml.setText("Reload");
        btnReloadXml.setMaximumSize(new java.awt.Dimension(80, 25));
        btnReloadXml.setMinimumSize(new java.awt.Dimension(80, 25));
        btnReloadXml.setPreferredSize(new java.awt.Dimension(80, 25));
        btnReloadXml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadXmlActionPerformed(evt);
            }
        });
        jPanel1.add(btnReloadXml);

        btnSaveXml.setFont(new java.awt.Font("Lucida Sans", 0, 10)); // NOI18N
        btnSaveXml.setText("Save");
        btnSaveXml.setMaximumSize(new java.awt.Dimension(80, 25));
        btnSaveXml.setMinimumSize(new java.awt.Dimension(80, 25));
        btnSaveXml.setPreferredSize(new java.awt.Dimension(80, 25));
        btnSaveXml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveXmlActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaveXml);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        txtXml.setColumns(20);
        txtXml.setRows(5);
        txtXml.setSyntaxEditingStyle("text/xml");
        jScrollPane2.setViewportView(txtXml);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReloadXmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadXmlActionPerformed

        reloadXml();

    }//GEN-LAST:event_btnReloadXmlActionPerformed

    private void btnSaveXmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveXmlActionPerformed

        saveXml();

    }//GEN-LAST:event_btnSaveXmlActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReloadXml;
    private javax.swing.JButton btnSaveXml;
    private javax.swing.JPanel jPanel1;
    private org.fife.ui.rsyntaxtextarea.RSyntaxTextArea txtXml;
    // End of variables declaration//GEN-END:variables

}
