/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgWait.java
 *
 * Created on Nov 17, 2010, 12:14:59 AM
 */

package jellyfish.base;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Xevia
 */
public class DlgWait extends javax.swing.JDialog {

    private Runnable hideShow = new Runnable() {

        public void run() {
            while (true) {
                if (visible!=DlgWait.this.isVisible()) {
                    DlgWait.this.setVisible(visible);
                }
                try {
                    Thread.sleep( 1000 );
                } catch ( InterruptedException ex ) {
                    Logger.getLogger( DlgWait.class.getName() ).log( Level.SEVERE, null, ex );
                }
            }
        }

    };

    private String currentTask;
    private boolean visible;
    private Thread hideShowThread;

    /** Creates new form DlgWait */
    public DlgWait(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        this.setLocationRelativeTo( parent );
//        this.hideShowThread = new Thread( hideShow );
    }

    public String getCurrentTask() {
        return currentTask;
    }

    public void setCurrentTask( String currentTask ) {
        this.currentTask = currentTask;
    }

    public void asycSetVisible(boolean visible) {
        if (!this.hideShowThread.isAlive())
            this.hideShowThread.start();
        this.visible = visible;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        txtTask = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        txtTask.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTask.setMaximumSize(new java.awt.Dimension(300, 20));
        txtTask.setMinimumSize(new java.awt.Dimension(300, 20));
        txtTask.setPreferredSize(new java.awt.Dimension(300, 20));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${currentTask}"), txtTask, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtTask, gridBagConstraints);

        progressBar.setIndeterminate(true);
        progressBar.setMaximumSize(new java.awt.Dimension(300, 20));
        progressBar.setMinimumSize(new java.awt.Dimension(300, 20));
        progressBar.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(progressBar, gridBagConstraints);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgWait dialog = new DlgWait(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel txtTask;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
